"""Seed the scrapers table with default scraper definitions."""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select
from api.database import async_session
from api.models.scraper import Scraper

DEFAULT_SCRAPERS = [
    # === SOCIAL PROFILES ===
    {
        "name": "reddit_profile",
        "display_name": "Reddit Profile",
        "description": "Extracts profile data from public Reddit profiles",
        "category": "social",
        "url_template": "https://www.reddit.com/user/{username}/about.json",
        "input_type": "username",
        "method": "GET",
        "headers": {"User-Agent": "xpose-tip/1.0"},
        "success_indicator": "\"name\":",
        "not_found_indicators": ["page not found", "\"error\": 404"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "data.name"},
            {"field": "karma", "type": "json_key", "pattern": "data.total_karma", "transform": "parse_int"},
            {"field": "created_utc", "type": "json_key", "pattern": "data.created_utc"},
            {"field": "bio", "type": "json_key", "pattern": "data.subreddit.public_description"},
            {"field": "avatar", "type": "json_key", "pattern": "data.icon_img"},
        ],
        "finding_title_template": "Reddit: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 2,
    },
    {
        "name": "github_scraper",
        "display_name": "GitHub Profile (scraper)",
        "description": "GitHub public profile via API",
        "category": "social",
        "url_template": "https://api.github.com/users/{username}",
        "input_type": "username",
        "method": "GET",
        "headers": {"Accept": "application/vnd.github+json"},
        "success_indicator": "\"login\":",
        "not_found_indicators": ["Not Found"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "name"},
            {"field": "bio", "type": "json_key", "pattern": "bio"},
            {"field": "location", "type": "json_key", "pattern": "location"},
            {"field": "company", "type": "json_key", "pattern": "company"},
            {"field": "blog", "type": "json_key", "pattern": "blog"},
            {"field": "avatar", "type": "json_key", "pattern": "avatar_url"},
            {"field": "public_repos", "type": "json_key", "pattern": "public_repos"},
            {"field": "followers", "type": "json_key", "pattern": "followers"},
            {"field": "twitter_username", "type": "json_key", "pattern": "twitter_username"},
        ],
        "finding_title_template": "GitHub (scraper): {display_name}",
        "finding_category": "social_account",
        "finding_severity": "medium",
        "rate_limit_requests": 10,
        "rate_limit_window": 60,
    },
    {
        "name": "steam_profile",
        "display_name": "Steam Profile",
        "description": "Steam gaming profile via XML API",
        "category": "social",
        "url_template": "https://steamcommunity.com/id/{username}/?xml=1",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "<steamID>",
        "not_found_indicators": ["The specified profile could not be found"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "<steamID><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "avatar", "type": "regex", "pattern": "<avatarFull><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "location", "type": "regex", "pattern": "<location><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "realname", "type": "regex", "pattern": "<realname><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "summary", "type": "regex", "pattern": "<summary><!\\[CDATA\\[(.+?)\\]\\]>", "transform": "strip_html"},
            {"field": "member_since", "type": "regex", "pattern": "<memberSince>(.+?)</memberSince>"},
        ],
        "finding_title_template": "Steam: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "keybase_profile",
        "display_name": "Keybase Profile",
        "description": "Keybase identity with linked proofs",
        "category": "social",
        "url_template": "https://keybase.io/_/api/1.0/user/lookup.json?usernames={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"status\":\\{\"code\":0",
        "not_found_indicators": ["\"them\":\\[null\\]", "\"code\":205"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "them.0.profile.full_name"},
            {"field": "bio", "type": "json_key", "pattern": "them.0.profile.bio"},
            {"field": "location", "type": "json_key", "pattern": "them.0.profile.location"},
            {"field": "avatar", "type": "json_key", "pattern": "them.0.pictures.primary.url"},
        ],
        "finding_title_template": "Keybase: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 2,
    },
    {
        "name": "medium_profile",
        "display_name": "Medium Profile",
        "description": "Medium blogging platform profile",
        "category": "social",
        "url_template": "https://medium.com/@{username}?format=json",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"username\":",
        "not_found_indicators": ["404", "Page not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "\"name\":\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "\"bio\":\"([^\"]+)\""},
            {"field": "followers", "type": "regex", "pattern": "\"usersFollowedByCount\":(\\d+)"},
            {"field": "twitter", "type": "regex", "pattern": "\"twitterScreenName\":\"([^\"]+)\""},
        ],
        "finding_title_template": "Medium: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "hackernews_profile",
        "display_name": "Hacker News Profile",
        "description": "Y Combinator Hacker News user profile",
        "category": "social",
        "url_template": "https://hacker-news.firebaseio.com/v0/user/{username}.json",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"id\":",
        "not_found_indicators": ["null"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "id"},
            {"field": "karma", "type": "json_key", "pattern": "karma"},
            {"field": "about", "type": "json_key", "pattern": "about", "transform": "strip_html"},
            {"field": "created", "type": "json_key", "pattern": "created"},
        ],
        "finding_title_template": "Hacker News: {display_name} (karma: {karma})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 5,
        "rate_limit_window": 10,
    },
    {
        "name": "devto_profile",
        "display_name": "Dev.to Profile",
        "description": "Dev.to developer community profile",
        "category": "social",
        "url_template": "https://dev.to/api/users/by_username?url={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"username\":",
        "not_found_indicators": ["Not Found", "404"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "name"},
            {"field": "bio", "type": "json_key", "pattern": "summary"},
            {"field": "location", "type": "json_key", "pattern": "location"},
            {"field": "avatar", "type": "json_key", "pattern": "profile_image"},
            {"field": "github_username", "type": "json_key", "pattern": "github_username"},
            {"field": "twitter_username", "type": "json_key", "pattern": "twitter_username"},
            {"field": "website_url", "type": "json_key", "pattern": "website_url"},
        ],
        "finding_title_template": "Dev.to: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 3,
        "rate_limit_window": 10,
    },
    {
        "name": "gitlab_profile",
        "display_name": "GitLab Profile",
        "description": "GitLab public user profile",
        "category": "social",
        "url_template": "https://gitlab.com/api/v4/users?username={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"id\":",
        "not_found_indicators": ["\\[\\]"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "0.name"},
            {"field": "bio", "type": "json_key", "pattern": "0.bio"},
            {"field": "location", "type": "json_key", "pattern": "0.location"},
            {"field": "avatar", "type": "json_key", "pattern": "0.avatar_url"},
            {"field": "website", "type": "json_key", "pattern": "0.website_url"},
        ],
        "finding_title_template": "GitLab: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 5,
        "rate_limit_window": 60,
    },
    # === BREACH LOOKUPS ===
    {
        "name": "xposedornot_scraper",
        "display_name": "XposedOrNot Breach Check",
        "description": "Free breach check via XposedOrNot API",
        "category": "breach",
        "url_template": "https://api.xposedornot.com/v1/check-email/{email}",
        "input_type": "email",
        "method": "GET",
        "success_indicator": "\"breaches_details\"",
        "not_found_indicators": ["Not found"],
        "extraction_rules": [
            {"field": "breach_count", "type": "json_key", "pattern": "breaches_details.breaches_count"},
            {"field": "exposed_data", "type": "json_key", "pattern": "breaches_details.exposed_data"},
            {"field": "first_breach", "type": "json_key", "pattern": "breaches_details.first_breach"},
        ],
        "finding_title_template": "XposedOrNot: {breach_count} breaches",
        "finding_category": "breach",
        "finding_severity": "high",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "leakcheck_public",
        "display_name": "LeakCheck Public",
        "description": "Public leak source check",
        "category": "breach",
        "url_template": "https://leakcheck.io/api/public?check={email}",
        "input_type": "email",
        "method": "GET",
        "success_indicator": "\"found\":",
        "not_found_indicators": ["\"found\":0"],
        "extraction_rules": [
            {"field": "found_count", "type": "json_key", "pattern": "found"},
            {"field": "sources", "type": "json_key", "pattern": "sources"},
        ],
        "finding_title_template": "LeakCheck: {found_count} leak sources",
        "finding_category": "breach",
        "finding_severity": "high",
        "rate_limit_requests": 1,
        "rate_limit_window": 10,
    },
    # === METADATA ===
    {
        "name": "gravatar_scraper",
        "display_name": "Gravatar Profile (scraper)",
        "description": "Gravatar profile via JSON API",
        "category": "metadata",
        "url_template": "https://en.gravatar.com/{username}.json",
        "input_type": "email",
        "input_transform": "email_to_username",
        "method": "GET",
        "success_indicator": "\"entry\":",
        "not_found_indicators": ["User not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "entry.0.displayName"},
            {"field": "username", "type": "json_key", "pattern": "entry.0.preferredUsername"},
            {"field": "about", "type": "json_key", "pattern": "entry.0.aboutMe"},
            {"field": "location", "type": "json_key", "pattern": "entry.0.currentLocation"},
            {"field": "avatar", "type": "json_key", "pattern": "entry.0.thumbnailUrl"},
            {"field": "profile_url", "type": "json_key", "pattern": "entry.0.profileUrl"},
        ],
        "finding_title_template": "Gravatar (scraper): {display_name}",
        "finding_category": "metadata",
        "finding_severity": "medium",
        "rate_limit_requests": 2,
        "rate_limit_window": 2,
    },
    # === DOMAIN INTEL ===
    {
        "name": "crtsh_subdomains",
        "display_name": "Certificate Transparency Subdomains",
        "description": "Subdomain discovery via crt.sh certificate transparency logs",
        "category": "metadata",
        "url_template": "https://crt.sh/?q=%.{domain}&output=json",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "\"common_name\":",
        "not_found_indicators": ["\\[\\]"],
        "extraction_rules": [
            {"field": "subdomains", "type": "regex", "pattern": "\"common_name\":\"([^\"]+)\""},
        ],
        "finding_title_template": "Certificate transparency: subdomains found",
        "finding_category": "metadata",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 10,
    },
    {
        "name": "securitytrails_ping",
        "display_name": "SecurityTrails DNS",
        "description": "Check SecurityTrails DNS history availability",
        "category": "metadata",
        "url_template": "https://securitytrails.com/domain/{domain}/dns",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "<title>.*DNS.*SecurityTrails",
        "not_found_indicators": ["Domain not found"],
        "extraction_rules": [
            {"field": "title", "type": "regex", "pattern": "<title>(.+?)</title>"},
        ],
        "finding_title_template": "SecurityTrails: DNS history available",
        "finding_category": "metadata",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    # === IDENTITY ESTIMATION ===
    {
        "name": "genderize",
        "display_name": "Genderize — Gender Prediction",
        "description": "Predicts gender from first name with confidence probability",
        "category": "identity",
        "url_template": "https://api.genderize.io/?name={first_name}",
        "input_type": "first_name",
        "method": "GET",
        "success_indicator": "\"gender\":",
        "not_found_indicators": ["\"gender\":null"],
        "extraction_rules": [
            {"field": "gender", "type": "json_key", "pattern": "gender"},
            {"field": "probability", "type": "json_key", "pattern": "probability"},
            {"field": "sample_count", "type": "json_key", "pattern": "count", "transform": "parse_int"},
        ],
        "finding_title_template": "Gender prediction: {gender} ({probability} confidence)",
        "finding_category": "identity",
        "finding_severity": "info",
        "rate_limit_requests": 10,
        "rate_limit_window": 60,
        "notes": "Free tier: 100 requests/day. No API key needed.",
    },
    {
        "name": "agify",
        "display_name": "Agify — Age Estimation",
        "description": "Estimates probable age from first name based on demographic data",
        "category": "identity",
        "url_template": "https://api.agify.io/?name={first_name}",
        "input_type": "first_name",
        "method": "GET",
        "success_indicator": "\"age\":",
        "not_found_indicators": ["\"age\":null"],
        "extraction_rules": [
            {"field": "age", "type": "json_key", "pattern": "age", "transform": "parse_int"},
            {"field": "sample_count", "type": "json_key", "pattern": "count", "transform": "parse_int"},
        ],
        "finding_title_template": "Age estimation: ~{age} years old",
        "finding_category": "identity",
        "finding_severity": "info",
        "rate_limit_requests": 10,
        "rate_limit_window": 60,
        "notes": "Free tier: 100 requests/day. No API key needed.",
    },
    {
        "name": "nationalize",
        "display_name": "Nationalize — Nationality Prediction",
        "description": "Predicts probable nationality/origin from first name",
        "category": "identity",
        "url_template": "https://api.nationalize.io/?name={first_name}",
        "input_type": "first_name",
        "method": "GET",
        "success_indicator": "\"country\":",
        "not_found_indicators": ["\"country\":[]"],
        "extraction_rules": [
            {"field": "top_country", "type": "json_key", "pattern": "country.0.country_id"},
            {"field": "top_probability", "type": "json_key", "pattern": "country.0.probability"},
            {"field": "second_country", "type": "json_key", "pattern": "country.1.country_id"},
            {"field": "second_probability", "type": "json_key", "pattern": "country.1.probability"},
            {"field": "third_country", "type": "json_key", "pattern": "country.2.country_id"},
            {"field": "sample_count", "type": "json_key", "pattern": "count", "transform": "parse_int"},
        ],
        "finding_title_template": "Nationality prediction: {top_country} ({top_probability})",
        "finding_category": "identity",
        "finding_severity": "info",
        "rate_limit_requests": 10,
        "rate_limit_window": 60,
        "notes": "Free tier: 100 requests/day. No API key needed.",
    },
    # === ARCHIVE / WAYBACK MACHINE ===
    {
        "name": "wayback_domain",
        "display_name": "Wayback Machine — Domain History",
        "description": "Checks Internet Archive for historical snapshots of the email domain",
        "category": "archive",
        "url_template": "https://web.archive.org/cdx/search/cdx?url={domain}&output=json&limit=1&fl=timestamp,original,statuscode&collapse=timestamp:6",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "\\[\\[",
        "not_found_indicators": ["[]", "Blocked"],
        "extraction_rules": [
            {"field": "first_snapshot", "type": "regex", "pattern": "\\[\"(\\d{14})\"", "group": 1},
            {"field": "url", "type": "regex", "pattern": "\"(https?://[^\"]+)\""},
        ],
        "finding_title_template": "Wayback Machine: domain archived since {first_snapshot}",
        "finding_category": "archive",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
        "notes": "Free, no auth. CDX API. Returns first snapshot date.",
    },
    {
        "name": "wayback_count",
        "display_name": "Wayback Machine — Snapshot Count",
        "description": "Counts total archived snapshots for the domain on archive.org",
        "category": "archive",
        "url_template": "https://web.archive.org/cdx/search/cdx?url={domain}/*&output=json&limit=0&showNumPages=true",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "\\d+",
        "not_found_indicators": ["0", "Blocked"],
        "extraction_rules": [
            {"field": "total_pages", "type": "regex", "pattern": "(\\d+)"},
        ],
        "finding_title_template": "Wayback Machine: {total_pages} archive pages found",
        "finding_category": "archive",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    {
        "name": "wayback_profile",
        "display_name": "Wayback Machine — Profile Archive",
        "description": "Checks if user profiles (twitter, github, etc.) have been archived",
        "category": "archive",
        "url_template": "https://web.archive.org/cdx/search/cdx?url=twitter.com/{username}&output=json&limit=1&fl=timestamp,original,statuscode",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\\[\\[",
        "not_found_indicators": ["[]", "Blocked"],
        "extraction_rules": [
            {"field": "first_archived", "type": "regex", "pattern": "\\[\"(\\d{14})\"", "group": 1},
            {"field": "archived_url", "type": "regex", "pattern": "\"(https?://[^\"]+)\""},
        ],
        "finding_title_template": "Archived profile found: Twitter since {first_archived}",
        "finding_category": "archive",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
        "notes": "Checks Twitter specifically. Additional platform scrapers can be added.",
    },
    # === SOCIAL PROFILE EXPANSION ===
    {
        "name": "aboutme_profile",
        "display_name": "About.me Profile",
        "description": "About.me personal landing page profile",
        "category": "social",
        "url_template": "https://about.me/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Page not found", "404"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "og:description\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "About.me: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "imgur_profile",
        "display_name": "Imgur Profile",
        "description": "Imgur image hosting platform profile",
        "category": "social",
        "url_template": "https://imgur.com/user/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Imgur. The magic of the Internet", "Page not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Imgur: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "mastodon_search",
        "display_name": "Mastodon / Fediverse",
        "description": "Search for accounts on Mastodon (mastodon.social instance)",
        "category": "social",
        "url_template": "https://mastodon.social/api/v2/search?q={username}&type=accounts&limit=3",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"accounts\":\\[{",
        "not_found_indicators": ["\"accounts\":[]"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "accounts.0.display_name"},
            {"field": "acct", "type": "json_key", "pattern": "accounts.0.acct"},
            {"field": "bio", "type": "json_key", "pattern": "accounts.0.note", "transform": "strip_html"},
            {"field": "avatar", "type": "json_key", "pattern": "accounts.0.avatar"},
            {"field": "followers", "type": "json_key", "pattern": "accounts.0.followers_count", "transform": "parse_int"},
            {"field": "url", "type": "json_key", "pattern": "accounts.0.url"},
        ],
        "finding_title_template": "Mastodon: {display_name} (@{acct})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 5,
        "notes": "Searches mastodon.social only. Federated search across instances is not supported.",
    },
    {
        "name": "stackoverflow_search",
        "display_name": "StackOverflow Profile",
        "description": "Search StackOverflow for user profiles by username",
        "category": "social",
        "url_template": "https://api.stackexchange.com/2.3/users?inname={username}&site=stackoverflow&pagesize=1&order=desc&sort=reputation",
        "input_type": "username",
        "method": "GET",
        "headers": {"Accept-Encoding": "gzip"},
        "success_indicator": "\"items\":\\[{",
        "not_found_indicators": ["\"items\":[]"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "items.0.display_name"},
            {"field": "reputation", "type": "json_key", "pattern": "items.0.reputation", "transform": "parse_int"},
            {"field": "avatar", "type": "json_key", "pattern": "items.0.profile_image"},
            {"field": "location", "type": "json_key", "pattern": "items.0.location"},
            {"field": "profile_url", "type": "json_key", "pattern": "items.0.link"},
        ],
        "finding_title_template": "StackOverflow: {display_name} (rep: {reputation})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 5,
        "rate_limit_window": 60,
        "notes": "StackExchange API returns gzip. httpx handles this automatically with follow_redirects.",
    },
    {
        "name": "pinterest_profile",
        "display_name": "Pinterest Profile",
        "description": "Pinterest visual discovery profile",
        "category": "social",
        "url_template": "https://www.pinterest.com/{username}/",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "pinterestapp:about",
        "not_found_indicators": ["404", "Page not found", "Hmm...this page doesn"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "pinterestapp:about\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Pinterest: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "linktree_profile",
        "display_name": "Linktree Profile",
        "description": "Linktree link-in-bio profile",
        "category": "social",
        "url_template": "https://linktr.ee/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Nothing to see here", "Page not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "og:description\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Linktree: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "disqus_profile",
        "display_name": "Disqus Comment Profile",
        "description": "Disqus commenting platform user profile",
        "category": "social",
        "url_template": "https://disqus.com/by/{username}/",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Page not found", "404"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "og:description\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Disqus: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    # === GAMING ===
    {
        "name": "lichess_profile",
        "display_name": "Lichess Chess Profile",
        "description": "Lichess online chess platform profile with rating and game stats",
        "category": "gaming",
        "url_template": "https://lichess.org/api/user/{username}",
        "input_type": "username",
        "method": "GET",
        "headers": {"Accept": "application/json"},
        "success_indicator": "\"username\":",
        "not_found_indicators": ["Not Found", "404"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "username"},
            {"field": "bio", "type": "json_key", "pattern": "profile.bio"},
            {"field": "location", "type": "json_key", "pattern": "profile.country"},
            {"field": "rating_blitz", "type": "json_key", "pattern": "perfs.blitz.rating", "transform": "parse_int"},
            {"field": "rating_rapid", "type": "json_key", "pattern": "perfs.rapid.rating", "transform": "parse_int"},
            {"field": "total_games", "type": "json_key", "pattern": "count.all", "transform": "parse_int"},
            {"field": "created", "type": "json_key", "pattern": "createdAt"},
        ],
        "finding_title_template": "Lichess: {display_name} (blitz: {rating_blitz})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 3,
        "rate_limit_window": 5,
    },
    {
        "name": "chesscom_profile",
        "display_name": "Chess.com Profile",
        "description": "Chess.com gaming profile with avatar, followers, and country",
        "category": "gaming",
        "url_template": "https://api.chess.com/pub/player/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"player_id\":",
        "not_found_indicators": ["Not Found", "\"code\":0"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "name"},
            {"field": "username", "type": "json_key", "pattern": "username"},
            {"field": "avatar", "type": "json_key", "pattern": "avatar"},
            {"field": "followers", "type": "json_key", "pattern": "followers", "transform": "parse_int"},
            {"field": "country", "type": "json_key", "pattern": "country"},
            {"field": "title", "type": "json_key", "pattern": "title"},
            {"field": "joined", "type": "json_key", "pattern": "joined"},
        ],
        "finding_title_template": "Chess.com: {display_name} ({followers} followers)",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 3,
        "rate_limit_window": 5,
    },
    {
        "name": "roblox_profile",
        "display_name": "Roblox Profile",
        "description": "Roblox gaming platform user search",
        "category": "gaming",
        "url_template": "https://users.roblox.com/v1/users/search?keyword={username}&limit=10",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"data\":\\[{",
        "not_found_indicators": ["\"data\":[]"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "data.0.displayName"},
            {"field": "username", "type": "json_key", "pattern": "data.0.name"},
            {"field": "user_id", "type": "json_key", "pattern": "data.0.id", "transform": "parse_int"},
            {"field": "verified", "type": "json_key", "pattern": "data.0.hasVerifiedBadge"},
        ],
        "finding_title_template": "Roblox: {display_name} (@{username})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 3,
        "rate_limit_window": 10,
    },
    {
        "name": "myanimelist_profile",
        "display_name": "MyAnimeList Profile",
        "description": "MyAnimeList anime/manga community profile via Jikan API",
        "category": "gaming",
        "url_template": "https://api.jikan.moe/v4/users/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"mal_id\":",
        "not_found_indicators": ["\"status\":404", "Resource does not exist"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "data.username"},
            {"field": "avatar", "type": "json_key", "pattern": "data.images.jpg.image_url"},
            {"field": "profile_url", "type": "json_key", "pattern": "data.url"},
            {"field": "last_online", "type": "json_key", "pattern": "data.last_online"},
            {"field": "joined", "type": "json_key", "pattern": "data.joined"},
        ],
        "finding_title_template": "MyAnimeList: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 4,
    },
    # === SOCIAL EXPANSION (Sprint 19) ===
    {
        "name": "twitch_profile",
        "display_name": "Twitch Profile",
        "description": "Twitch live streaming platform profile",
        "category": "social",
        "url_template": "https://www.twitch.tv/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Sorry. Unless you've got a time machine", "content=\"Twitch\""],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+?)\\s*-\\s*Twitch\""},
            {"field": "bio", "type": "regex", "pattern": "og:description\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Twitch: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 5,
    },
    {
        "name": "telegram_profile",
        "display_name": "Telegram Profile",
        "description": "Telegram messaging platform public profile",
        "category": "social",
        "url_template": "https://t.me/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["you can contact <strong>@"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "og:description\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Telegram: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "letterboxd_profile",
        "display_name": "Letterboxd Profile",
        "description": "Letterboxd film review platform profile",
        "category": "social",
        "url_template": "https://letterboxd.com/{username}/",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Page Not Found", "404"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+?)(?:'s profile)?\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "Letterboxd: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "buymeacoffee_profile",
        "display_name": "Buy Me a Coffee",
        "description": "Buy Me a Coffee creator support platform profile",
        "category": "social",
        "url_template": "https://buymeacoffee.com/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "og:title",
        "not_found_indicators": ["Page not found", "404", "not available"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "og:title\" content=\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "og:description\" content=\"([^\"]+)\""},
            {"field": "avatar", "type": "regex", "pattern": "og:image\" content=\"([^\"]+)\""},
        ],
        "finding_title_template": "BuyMeACoffee: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "mixcloud_profile",
        "display_name": "Mixcloud Profile",
        "description": "Mixcloud music streaming and DJ mix platform profile",
        "category": "social",
        "url_template": "https://api.mixcloud.com/{username}/",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"username\":",
        "not_found_indicators": ["\"error\"", "Not Found"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "name"},
            {"field": "username", "type": "json_key", "pattern": "username"},
            {"field": "avatar", "type": "json_key", "pattern": "pictures.large"},
            {"field": "bio", "type": "json_key", "pattern": "biog", "transform": "strip_html"},
            {"field": "city", "type": "json_key", "pattern": "city"},
            {"field": "country", "type": "json_key", "pattern": "country"},
        ],
        "finding_title_template": "Mixcloud: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "duolingo_profile",
        "display_name": "Duolingo Profile",
        "description": "Duolingo language learning platform profile",
        "category": "social",
        "url_template": "https://www.duolingo.com/2017-06-30/users?username={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"users\":\\[{",
        "not_found_indicators": ["\"users\":[]"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "users.0.username"},
            {"field": "avatar", "type": "json_key", "pattern": "users.0.picture"},
            {"field": "streak", "type": "json_key", "pattern": "users.0.streak", "transform": "parse_int"},
            {"field": "total_xp", "type": "json_key", "pattern": "users.0.totalXp", "transform": "parse_int"},
        ],
        "finding_title_template": "Duolingo: {display_name} (streak: {streak})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    {
        "name": "pastebin_user",
        "display_name": "Pastebin User Profile",
        "description": "Pastebin paste sharing platform user profile",
        "category": "social",
        "url_template": "https://pastebin.com/u/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "<title>.*?'s Pastebin",
        "not_found_indicators": ["Not Found", "404", "User does not exist"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "<title>([^']+)'s Pastebin"},
            {"field": "avatar", "type": "regex", "pattern": "\"user-icon\".*?src=\"([^\"]+)\""},
        ],
        "finding_title_template": "Pastebin: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "medium",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    {
        "name": "dockerhub_profile",
        "display_name": "Docker Hub Profile",
        "description": "Docker Hub container registry user profile",
        "category": "social",
        "url_template": "https://hub.docker.com/v2/users/{username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"id\":",
        "not_found_indicators": ["User not found", "Object not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "full_name"},
            {"field": "username", "type": "json_key", "pattern": "username"},
            {"field": "avatar", "type": "json_key", "pattern": "gravatar_url"},
            {"field": "location", "type": "json_key", "pattern": "location"},
            {"field": "company", "type": "json_key", "pattern": "company"},
            {"field": "joined", "type": "json_key", "pattern": "date_joined"},
        ],
        "finding_title_template": "Docker Hub: {display_name} (@{username})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 3,
        "rate_limit_window": 10,
    },
    # === ARCHIVE EXPANSION (Sprint 19) ===
    {
        "name": "wayback_linkedin",
        "display_name": "Wayback Machine \u2014 LinkedIn Archive",
        "description": "Check if LinkedIn profile has been archived on archive.org",
        "category": "archive",
        "url_template": "https://web.archive.org/cdx/search/cdx?url=linkedin.com/in/{username}&output=json&limit=1&fl=timestamp,original,statuscode",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\\[\\[",
        "not_found_indicators": ["[]", "Blocked"],
        "extraction_rules": [
            {"field": "first_archived", "type": "regex", "pattern": "\\[\"(\\d{14})\"", "group": 1},
            {"field": "archived_url", "type": "regex", "pattern": "\"(https?://[^\"]+)\""},
        ],
        "finding_title_template": "LinkedIn archived since {first_archived}",
        "finding_category": "archive",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    {
        "name": "wayback_facebook",
        "display_name": "Wayback Machine \u2014 Facebook Archive",
        "description": "Check if Facebook profile has been archived on archive.org",
        "category": "archive",
        "url_template": "https://web.archive.org/cdx/search/cdx?url=facebook.com/{username}&output=json&limit=1&fl=timestamp,original,statuscode",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\\[\\[",
        "not_found_indicators": ["[]", "Blocked"],
        "extraction_rules": [
            {"field": "first_archived", "type": "regex", "pattern": "\\[\"(\\d{14})\"", "group": 1},
            {"field": "archived_url", "type": "regex", "pattern": "\"(https?://[^\"]+)\""},
        ],
        "finding_title_template": "Facebook archived since {first_archived}",
        "finding_category": "archive",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    {
        "name": "wayback_github",
        "display_name": "Wayback Machine \u2014 GitHub Archive",
        "description": "Check if GitHub profile has been archived on archive.org",
        "category": "archive",
        "url_template": "https://web.archive.org/cdx/search/cdx?url=github.com/{username}&output=json&limit=1&fl=timestamp,original,statuscode",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\\[\\[",
        "not_found_indicators": ["[]", "Blocked"],
        "extraction_rules": [
            {"field": "first_archived", "type": "regex", "pattern": "\\[\"(\\d{14})\"", "group": 1},
            {"field": "archived_url", "type": "regex", "pattern": "\"(https?://[^\"]+)\""},
        ],
        "finding_title_template": "GitHub archived since {first_archived}",
        "finding_category": "archive",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    # === ENRICHMENT / PEOPLE SEARCH ===
    {
        "name": "psbdmp_search",
        "display_name": "Pastebin Dump Search",
        "description": "Search for email mentions in public pastebin dumps via psbdmp.ws",
        "category": "breach",
        "url_template": "https://psbdmp.ws/api/v3/search/{email}",
        "input_type": "email",
        "method": "GET",
        "success_indicator": "\"data\":",
        "not_found_indicators": ["\"data\":[]", "Not found", "null"],
        "extraction_rules": [
            {"field": "dump_count", "type": "regex", "pattern": "\"id\":", "transform": "parse_int"},
            {"field": "first_dump_id", "type": "json_key", "pattern": "data.0.id"},
            {"field": "first_dump_tags", "type": "json_key", "pattern": "data.0.tags"},
        ],
        "finding_title_template": "Pastebin dumps: email found in paste archives",
        "finding_category": "breach",
        "finding_severity": "high",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
    {
        "name": "disposable_email_check",
        "display_name": "Disposable Email Detection",
        "description": "Checks if email domain is a known disposable/temporary email provider",
        "category": "metadata",
        "url_template": "https://open.kickbox.com/v1/disposable/{domain}",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "\"disposable\":",
        "not_found_indicators": [],
        "extraction_rules": [
            {"field": "is_disposable", "type": "json_key", "pattern": "disposable"},
        ],
        "finding_title_template": "Disposable email: {is_disposable}",
        "finding_category": "metadata",
        "finding_severity": "medium",
        "rate_limit_requests": 5,
        "rate_limit_window": 10,
        "notes": "Severity medium only if disposable=true. Free, no auth.",
    },
]


async def seed():
    async with async_session() as session:
        for scraper_data in DEFAULT_SCRAPERS:
            result = await session.execute(
                select(Scraper).where(Scraper.name == scraper_data["name"])
            )
            existing = result.scalar_one_or_none()
            if existing:
                for key, value in scraper_data.items():
                    if key != "name":
                        setattr(existing, key, value)
            else:
                session.add(Scraper(**scraper_data))
        await session.commit()
        print(f"Seeded {len(DEFAULT_SCRAPERS)} scrapers.")


if __name__ == "__main__":
    asyncio.run(seed())
