"""Seed the scrapers table with default scraper definitions."""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select
from api.database import async_session
from api.models.scraper import Scraper

DEFAULT_SCRAPERS = [
    # === SOCIAL PROFILES ===
    {
        "name": "reddit_profile",
        "display_name": "Reddit Profile",
        "description": "Extracts profile data from public Reddit profiles",
        "category": "social",
        "url_template": "https://www.reddit.com/user/{username}/about.json",
        "input_type": "username",
        "method": "GET",
        "headers": {"User-Agent": "xpose-tip/1.0"},
        "success_indicator": "\"name\":",
        "not_found_indicators": ["page not found", "\"error\": 404"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "data.name"},
            {"field": "karma", "type": "json_key", "pattern": "data.total_karma", "transform": "parse_int"},
            {"field": "created_utc", "type": "json_key", "pattern": "data.created_utc"},
            {"field": "bio", "type": "json_key", "pattern": "data.subreddit.public_description"},
            {"field": "avatar", "type": "json_key", "pattern": "data.icon_img"},
        ],
        "finding_title_template": "Reddit: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 2,
    },
    {
        "name": "github_scraper",
        "display_name": "GitHub Profile (scraper)",
        "description": "GitHub public profile via API",
        "category": "social",
        "url_template": "https://api.github.com/users/{username}",
        "input_type": "username",
        "method": "GET",
        "headers": {"Accept": "application/vnd.github+json"},
        "success_indicator": "\"login\":",
        "not_found_indicators": ["Not Found"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "name"},
            {"field": "bio", "type": "json_key", "pattern": "bio"},
            {"field": "location", "type": "json_key", "pattern": "location"},
            {"field": "company", "type": "json_key", "pattern": "company"},
            {"field": "blog", "type": "json_key", "pattern": "blog"},
            {"field": "avatar", "type": "json_key", "pattern": "avatar_url"},
            {"field": "public_repos", "type": "json_key", "pattern": "public_repos"},
            {"field": "followers", "type": "json_key", "pattern": "followers"},
            {"field": "twitter_username", "type": "json_key", "pattern": "twitter_username"},
        ],
        "finding_title_template": "GitHub (scraper): {display_name}",
        "finding_category": "social_account",
        "finding_severity": "medium",
        "rate_limit_requests": 10,
        "rate_limit_window": 60,
    },
    {
        "name": "steam_profile",
        "display_name": "Steam Profile",
        "description": "Steam gaming profile via XML API",
        "category": "social",
        "url_template": "https://steamcommunity.com/id/{username}/?xml=1",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "<steamID>",
        "not_found_indicators": ["The specified profile could not be found"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "<steamID><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "avatar", "type": "regex", "pattern": "<avatarFull><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "location", "type": "regex", "pattern": "<location><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "realname", "type": "regex", "pattern": "<realname><!\\[CDATA\\[(.+?)\\]\\]>"},
            {"field": "summary", "type": "regex", "pattern": "<summary><!\\[CDATA\\[(.+?)\\]\\]>", "transform": "strip_html"},
            {"field": "member_since", "type": "regex", "pattern": "<memberSince>(.+?)</memberSince>"},
        ],
        "finding_title_template": "Steam: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 3,
    },
    {
        "name": "keybase_profile",
        "display_name": "Keybase Profile",
        "description": "Keybase identity with linked proofs",
        "category": "social",
        "url_template": "https://keybase.io/_/api/1.0/user/lookup.json?usernames={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"status\":\\{\"code\":0",
        "not_found_indicators": ["\"them\":\\[null\\]", "\"code\":205"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "them.0.profile.full_name"},
            {"field": "bio", "type": "json_key", "pattern": "them.0.profile.bio"},
            {"field": "location", "type": "json_key", "pattern": "them.0.profile.location"},
            {"field": "avatar", "type": "json_key", "pattern": "them.0.pictures.primary.url"},
        ],
        "finding_title_template": "Keybase: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 2,
        "rate_limit_window": 2,
    },
    {
        "name": "medium_profile",
        "display_name": "Medium Profile",
        "description": "Medium blogging platform profile",
        "category": "social",
        "url_template": "https://medium.com/@{username}?format=json",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"username\":",
        "not_found_indicators": ["404", "Page not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "regex", "pattern": "\"name\":\"([^\"]+)\""},
            {"field": "bio", "type": "regex", "pattern": "\"bio\":\"([^\"]+)\""},
            {"field": "followers", "type": "regex", "pattern": "\"usersFollowedByCount\":(\\d+)"},
            {"field": "twitter", "type": "regex", "pattern": "\"twitterScreenName\":\"([^\"]+)\""},
        ],
        "finding_title_template": "Medium: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "hackernews_profile",
        "display_name": "Hacker News Profile",
        "description": "Y Combinator Hacker News user profile",
        "category": "social",
        "url_template": "https://hacker-news.firebaseio.com/v0/user/{username}.json",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"id\":",
        "not_found_indicators": ["null"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "id"},
            {"field": "karma", "type": "json_key", "pattern": "karma"},
            {"field": "about", "type": "json_key", "pattern": "about", "transform": "strip_html"},
            {"field": "created", "type": "json_key", "pattern": "created"},
        ],
        "finding_title_template": "Hacker News: {display_name} (karma: {karma})",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 5,
        "rate_limit_window": 10,
    },
    {
        "name": "devto_profile",
        "display_name": "Dev.to Profile",
        "description": "Dev.to developer community profile",
        "category": "social",
        "url_template": "https://dev.to/api/users/by_username?url={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"username\":",
        "not_found_indicators": ["Not Found", "404"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "name"},
            {"field": "bio", "type": "json_key", "pattern": "summary"},
            {"field": "location", "type": "json_key", "pattern": "location"},
            {"field": "avatar", "type": "json_key", "pattern": "profile_image"},
            {"field": "github_username", "type": "json_key", "pattern": "github_username"},
            {"field": "twitter_username", "type": "json_key", "pattern": "twitter_username"},
            {"field": "website_url", "type": "json_key", "pattern": "website_url"},
        ],
        "finding_title_template": "Dev.to: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 3,
        "rate_limit_window": 10,
    },
    {
        "name": "gitlab_profile",
        "display_name": "GitLab Profile",
        "description": "GitLab public user profile",
        "category": "social",
        "url_template": "https://gitlab.com/api/v4/users?username={username}",
        "input_type": "username",
        "method": "GET",
        "success_indicator": "\"id\":",
        "not_found_indicators": ["\\[\\]"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "0.name"},
            {"field": "bio", "type": "json_key", "pattern": "0.bio"},
            {"field": "location", "type": "json_key", "pattern": "0.location"},
            {"field": "avatar", "type": "json_key", "pattern": "0.avatar_url"},
            {"field": "website", "type": "json_key", "pattern": "0.website_url"},
        ],
        "finding_title_template": "GitLab: {display_name}",
        "finding_category": "social_account",
        "finding_severity": "low",
        "rate_limit_requests": 5,
        "rate_limit_window": 60,
    },
    # === BREACH LOOKUPS ===
    {
        "name": "xposedornot_scraper",
        "display_name": "XposedOrNot Breach Check",
        "description": "Free breach check via XposedOrNot API",
        "category": "breach",
        "url_template": "https://api.xposedornot.com/v1/check-email/{email}",
        "input_type": "email",
        "method": "GET",
        "success_indicator": "\"breaches_details\"",
        "not_found_indicators": ["Not found"],
        "extraction_rules": [
            {"field": "breach_count", "type": "json_key", "pattern": "breaches_details.breaches_count"},
            {"field": "exposed_data", "type": "json_key", "pattern": "breaches_details.exposed_data"},
            {"field": "first_breach", "type": "json_key", "pattern": "breaches_details.first_breach"},
        ],
        "finding_title_template": "XposedOrNot: {breach_count} breaches",
        "finding_category": "breach",
        "finding_severity": "high",
        "rate_limit_requests": 1,
        "rate_limit_window": 3,
    },
    {
        "name": "leakcheck_public",
        "display_name": "LeakCheck Public",
        "description": "Public leak source check",
        "category": "breach",
        "url_template": "https://leakcheck.io/api/public?check={email}",
        "input_type": "email",
        "method": "GET",
        "success_indicator": "\"found\":",
        "not_found_indicators": ["\"found\":0"],
        "extraction_rules": [
            {"field": "found_count", "type": "json_key", "pattern": "found"},
            {"field": "sources", "type": "json_key", "pattern": "sources"},
        ],
        "finding_title_template": "LeakCheck: {found_count} leak sources",
        "finding_category": "breach",
        "finding_severity": "high",
        "rate_limit_requests": 1,
        "rate_limit_window": 10,
    },
    # === METADATA ===
    {
        "name": "gravatar_scraper",
        "display_name": "Gravatar Profile (scraper)",
        "description": "Gravatar profile via JSON API",
        "category": "metadata",
        "url_template": "https://en.gravatar.com/{username}.json",
        "input_type": "email",
        "input_transform": "email_to_username",
        "method": "GET",
        "success_indicator": "\"entry\":",
        "not_found_indicators": ["User not found"],
        "extraction_rules": [
            {"field": "display_name", "type": "json_key", "pattern": "entry.0.displayName"},
            {"field": "username", "type": "json_key", "pattern": "entry.0.preferredUsername"},
            {"field": "about", "type": "json_key", "pattern": "entry.0.aboutMe"},
            {"field": "location", "type": "json_key", "pattern": "entry.0.currentLocation"},
            {"field": "avatar", "type": "json_key", "pattern": "entry.0.thumbnailUrl"},
            {"field": "profile_url", "type": "json_key", "pattern": "entry.0.profileUrl"},
        ],
        "finding_title_template": "Gravatar (scraper): {display_name}",
        "finding_category": "metadata",
        "finding_severity": "medium",
        "rate_limit_requests": 2,
        "rate_limit_window": 2,
    },
    # === DOMAIN INTEL ===
    {
        "name": "crtsh_subdomains",
        "display_name": "Certificate Transparency Subdomains",
        "description": "Subdomain discovery via crt.sh certificate transparency logs",
        "category": "metadata",
        "url_template": "https://crt.sh/?q=%.{domain}&output=json",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "\"common_name\":",
        "not_found_indicators": ["\\[\\]"],
        "extraction_rules": [
            {"field": "subdomains", "type": "regex", "pattern": "\"common_name\":\"([^\"]+)\""},
        ],
        "finding_title_template": "Certificate transparency: subdomains found",
        "finding_category": "metadata",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 10,
    },
    {
        "name": "securitytrails_ping",
        "display_name": "SecurityTrails DNS",
        "description": "Check SecurityTrails DNS history availability",
        "category": "metadata",
        "url_template": "https://securitytrails.com/domain/{domain}/dns",
        "input_type": "domain",
        "input_transform": "email_to_domain",
        "method": "GET",
        "success_indicator": "<title>.*DNS.*SecurityTrails",
        "not_found_indicators": ["Domain not found"],
        "extraction_rules": [
            {"field": "title", "type": "regex", "pattern": "<title>(.+?)</title>"},
        ],
        "finding_title_template": "SecurityTrails: DNS history available",
        "finding_category": "metadata",
        "finding_severity": "info",
        "rate_limit_requests": 1,
        "rate_limit_window": 5,
    },
]


async def seed():
    async with async_session() as session:
        for scraper_data in DEFAULT_SCRAPERS:
            result = await session.execute(
                select(Scraper).where(Scraper.name == scraper_data["name"])
            )
            existing = result.scalar_one_or_none()
            if existing:
                for key, value in scraper_data.items():
                    if key != "name":
                        setattr(existing, key, value)
            else:
                session.add(Scraper(**scraper_data))
        await session.commit()
        print(f"Seeded {len(DEFAULT_SCRAPERS)} scrapers.")


if __name__ == "__main__":
    asyncio.run(seed())
