"""Seed the modules table with all xpose scanner modules."""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select
from api.database import async_session
from api.models.module import Module

MODULES = [
    # Layer 1 — Passive recon (enabled)
    {
        "id": "email_validator",
        "display_name": "Email Validator",
        "description": "Validates email format, checks MX records, detects disposable providers",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 60, "cooldown_sec": 1},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "holehe",
        "display_name": "Holehe",
        "description": "Email-to-account enumeration across 120+ services",
        "layer": 1,
        "category": "social",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.61",
    },
    {
        "id": "maigret",
        "display_name": "Maigret",
        "description": "Username enumeration across 2500+ sites",
        "layer": 1,
        "category": "social",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "0.4.4",
    },
    {
        "id": "sherlock",
        "display_name": "Sherlock",
        "description": "Username search across 400+ social networks",
        "layer": 1,
        "category": "social",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 5, "cooldown_sec": 10},
        "supported_regions": ["*"],
        "version": "0.14.3",
    },
    {
        "id": "ghunt",
        "display_name": "GHunt",
        "description": "Google account metadata extraction (requires DroidGuard patch)",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": True,
        "auth_config": {"note": "Requires DroidGuard patched credentials"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "2.0.0",
    },
    {
        "id": "hibp",
        "display_name": "Have I Been Pwned",
        "description": "Breach history lookup via HIBP API",
        "layer": 1,
        "category": "breach",
        "enabled": True,
        "requires_auth": True,
        "auth_config": {"api_key_env": "HIBP_API_KEY"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 6},
        "supported_regions": ["*"],
        "version": "3.0",
    },
    {
        "id": "h8mail",
        "display_name": "h8mail",
        "description": "Email breach and credential leak search",
        "layer": 1,
        "category": "breach",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "2.5.6",
    },
    {
        "id": "gravatar",
        "display_name": "Gravatar",
        "description": "Gravatar profile, avatar, and linked social accounts via email hash",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 60, "cooldown_sec": 1},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "social_enricher",
        "display_name": "Social Enricher",
        "description": "GitHub profile enrichment — name, bio, location, repos, followers",
        "layer": 1,
        "category": "social_account",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "emailrep",
        "display_name": "Email Reputation",
        "description": "Email reputation, breach status, social profiles, and domain security via emailrep.io (free, no key)",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 60, "cooldown_sec": 1},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "epieos",
        "display_name": "Epieos Google",
        "description": "Google account discovery — ID, name, profile photo from email via epieos.com (free)",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "fullcontact",
        "display_name": "FullContact",
        "description": "Person enrichment — name, age, gender, social profiles, company (requires API key)",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": True,
        "auth_config": {"api_key_env": "FULLCONTACT_API_KEY"},
        "rate_limit": {"rpm": 60, "cooldown_sec": 1},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "github_deep",
        "display_name": "GitHub Deep",
        "description": "Full GitHub profile, events, gists, alternate emails from commits (free public API)",
        "layer": 1,
        "category": "social_account",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "username_hunter",
        "display_name": "Username Hunter",
        "description": "Generate username permutations and check Reddit, Steam, Keybase, GitLab, Medium, HackerNews, Dev.to",
        "layer": 1,
        "category": "social_account",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "google_profile",
        "display_name": "Google Profile",
        "description": "Gmail/Google Workspace detection and YouTube presence search",
        "layer": 1,
        "category": "metadata",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 15, "cooldown_sec": 4},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "scraper_engine",
        "display_name": "Scraper Engine",
        "description": "Modular scraping framework — executes DB-defined scrapers with editable regex patterns",
        "layer": 1,
        "category": "social",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    # Layer 2 — Public databases (disabled by default)
    {
        "id": "maxmind_geo",
        "display_name": "MaxMind GeoIP",
        "description": "IP geolocation via MaxMind GeoLite2 local database",
        "layer": 2,
        "category": "geolocation",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "MAXMIND_LICENSE"},
        "rate_limit": {"rpm": 120, "cooldown_sec": 0},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "geoip",
        "display_name": "Free GeoIP",
        "description": "IP geolocation via ip-api.com — no API key needed, 45 req/min",
        "layer": 2,
        "category": "geolocation",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 45, "cooldown_sec": 1.5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "leaked_domains",
        "display_name": "Leaked Domains",
        "description": "Free breach check via XposedOrNot — breach history, exposed data types, industry analysis",
        "layer": 2,
        "category": "breach",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "dns_deep",
        "display_name": "DNS Intelligence",
        "description": "SPF, DMARC, DKIM, MX, NS analysis — email security posture assessment",
        "layer": 2,
        "category": "metadata",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 60, "cooldown_sec": 1},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "whois_lookup",
        "display_name": "WHOIS Lookup",
        "description": "Domain registration and ownership data",
        "layer": 2,
        "category": "domain_registration",
        "enabled": False,
        "requires_auth": False,
        "rate_limit": {"rpm": 20, "cooldown_sec": 3},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "databroker_check",
        "display_name": "Data Broker Check",
        "description": "Check presence on data broker sites (Spokeo, WhitePages, BeenVerified, etc.)",
        "layer": 2,
        "category": "data_broker",
        "enabled": False,
        "requires_auth": False,
        "rate_limit": {"rpm": 5, "cooldown_sec": 12},
        "supported_regions": ["US", "UK", "CA", "AU"],
        "version": "1.0.0",
    },
    {
        "id": "paste_monitor",
        "display_name": "Paste Monitor",
        "description": "Search for email/username in public paste sites",
        "layer": 2,
        "category": "paste",
        "enabled": False,
        "requires_auth": False,
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "virustotal",
        "display_name": "VirusTotal",
        "description": "Domain reputation, malware detection, SSL certificates, subdomains via VirusTotal API",
        "layer": 2,
        "category": "metadata",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "VIRUSTOTAL_API_KEY"},
        "rate_limit": {"rpm": 4, "cooldown_sec": 15},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "shodan",
        "display_name": "Shodan",
        "description": "Domain DNS, subdomains, IP ports, services, OS, vulnerabilities via Shodan API",
        "layer": 2,
        "category": "metadata",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "SHODAN_API_KEY"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 6},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "intelx",
        "display_name": "Intelligence X",
        "description": "Darkweb, paste, breach, and document search via Intelligence X API",
        "layer": 2,
        "category": "breach",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "INTELX_API_KEY"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 6},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "hunter",
        "display_name": "Hunter.io",
        "description": "Email discovery, domain search, email verification via Hunter.io API",
        "layer": 2,
        "category": "metadata",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "HUNTER_API_KEY"},
        "rate_limit": {"rpm": 15, "cooldown_sec": 4},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "dehashed",
        "display_name": "Dehashed",
        "description": "Credential search — hashed passwords, IPs, usernames, phone numbers via Dehashed API",
        "layer": 2,
        "category": "breach",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "DEHASHED_API_KEY"},
        "rate_limit": {"rpm": 5, "cooldown_sec": 12},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    # Layer 1 — Reverse image search
    {
        "id": "reverse_image",
        "display_name": "Reverse Image Search",
        "description": "Find profile photo matches across the web via PimEyes + TinEye",
        "layer": 1,
        "category": "metadata",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"api_key_env": "PIMEYES_API_KEY"},
        "rate_limit": {"rpm": 5, "cooldown_sec": 12},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    # Layer 3 — Voluntary audit / SaaS connectors (disabled by default)
    {
        "id": "google_audit",
        "display_name": "Google Account Audit",
        "description": "Audit Google account — connected apps, scopes, profile data (OAuth required)",
        "layer": 3,
        "category": "app_permission",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"oauth_provider": "google"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "microsoft_audit",
        "display_name": "Microsoft Account Audit",
        "description": "Audit Microsoft account — OAuth app grants, profile, device list (OAuth required)",
        "layer": 3,
        "category": "app_permission",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"oauth_provider": "microsoft"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "google_auditor",
        "display_name": "Google Account Auditor (Legacy)",
        "description": "Legacy placeholder — replaced by google_audit",
        "layer": 3,
        "category": "app_permission",
        "enabled": False,
        "requires_auth": True,
        "auth_config": {"oauth_provider": "google"},
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "exodus_tracker",
        "display_name": "Exodus Tracker Audit",
        "description": "Check apps for known trackers using Exodus Privacy database",
        "layer": 3,
        "category": "tracking",
        "enabled": False,
        "requires_auth": False,
        "rate_limit": {"rpm": 30, "cooldown_sec": 2},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    {
        "id": "browser_auditor",
        "display_name": "Browser Audit",
        "description": "Audit browser extensions, cookies, and tracking exposure",
        "layer": 3,
        "category": "browser_data",
        "enabled": False,
        "requires_auth": False,
        "rate_limit": {"rpm": 10, "cooldown_sec": 5},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
    # Layer 4 — Intelligence engine (always enabled, virtual module)
    {
        "id": "intelligence",
        "display_name": "Intelligence Engine",
        "description": "Automated analysis: IP deep dive, domain security, username correlation, breach cross-ref, risk assessment",
        "layer": 4,
        "category": "intelligence",
        "enabled": True,
        "requires_auth": False,
        "rate_limit": {"rpm": 100, "cooldown_sec": 0},
        "supported_regions": ["*"],
        "version": "1.0.0",
    },
]


async def seed():
    async with async_session() as session:
        for mod_data in MODULES:
            result = await session.execute(select(Module).where(Module.id == mod_data["id"]))
            existing = result.scalar_one_or_none()
            if existing:
                for key, value in mod_data.items():
                    if key != "id":
                        setattr(existing, key, value)
            else:
                session.add(Module(**mod_data))
        await session.commit()
        print(f"Seeded {len(MODULES)} modules.")


if __name__ == "__main__":
    asyncio.run(seed())
